### ISSUE TITLE
Issuing certificate as Secret does not exist

### ISSUE THREAD

**Issue by xioobu** [wjiec/alidns-webhook#21]
```shell
Status:
  Conditions:
    Last Transition Time:        2024-06-19T03:57:50Z
    Message:                     Issuing certificate as Secret does not exist
    Observed Generation:         1
    Reason:                      DoesNotExist
    Status:                      False
    Type:                        Ready
    Last Transition Time:        2024-06-19T03:57:50Z
    Message:                     Issuing certificate as Secret does not exist
    Observed Generation:         1
    Reason:                      DoesNotExist
    Status:                      True
    Type:                        Issuing
  Next Private Key Secret Name:  stat-xioobu-cn.tls-5s8qm
Events:                          <none>
root@lax:~/.laf/mydeploy# kubectl get certificate
NAME                 READY   SECRET               AGE
stat-xioobu-cn.tls   False   stat-xioobu-cn.tls   118m
root@lax:~/.laf/mydeploy# kubectl get secret
NAME                       TYPE     DATA   AGE
stat-xioobu-cn.tls-5s8qm   Opaque   1      118m
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: alidns-secret
  namespace: cert-manager
stringData:
  access-key-id: ""
  access-key-secret: ""
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: xioobu-acme
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: liz3002@126.com # Change ME
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: xioobu-acme
    solvers:
      - dns01:
          webhook:
            groupName: acme.xioobu.cn # Change ME
            solverName: alidns
            config:
              accessKeyIdRef:
                name: alidns-secret
                key: access-key-id
              accessKeySecretRef:
                name: alidns-secret
                key: access-key-secret
```

```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: stat-xxx-cn
  annotations:
    cert-manager.io/cluster-issuer: "xxx-acme"
    # cert-manager.io/issuer: "example-acme"
spec:
  tls:
  - hosts:
    - laf.xxx.cn
    secretName: stat-xxx-cn.tls
  rules:
  - host: laf.xxx.cn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              name: http
```
